config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='portfolio'

urlpatterns = [
    path('', views.home_view, name="home"),
    path('projetos/', views.projects_view, name="projetos"),
    path('tecnologias/', views.technologys_view, name="tecnologias"),
    path('laboratorios/', views.labs_view, name="laboratorios"),
    path('tecnologiasusadas/', views.usedtech_view, name="tecusada"),
    path('javascript/', views.javascript_view, name="javascript"),
    path('licenciatura/', views.university_view, name="licenciatura"),
    path('educacao/', views.education_view, name="educacao"),
    path('skills/', views.skills_view, name="skills"),
    path('hobbies/', views.hobbies_view, name="hobbies"),
    path('sobre/', views.aboutme_view, name="sobre"),
    path('blog', views.blog_view, name='blog'),
    path('contacto/', views.contact_view, name="contacto"),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('criar/', views.criar_post, name='criar'),
    path('editar/<int:comentario_id>', views.edita_comentario, name='editar'),
    path('apagar/<int:comentario_id>', views.apagar_comentario, name='apagar'),
    path('criarcadeira/', views.criar_cadeira, name='criarcadeira'),
    path('apagarcadeira/<int:cadeira_id>', views.apagar_cadeira, name='apagarcadeira'),
    path('criarprojeto/', views.criar_projeto, name='criarprojeto'),
    path('apagarprojeto/<int:projeto_id>', views.apagar_projeto, name='apagarprojeto'),
]

portfolio/models.py
from django.db import models

# Create your models here.

#CRIAÇÃO BASES DADOS


class Pessoa(models.Model):
   

    funcao = [
        ('aluno', 'Aluno'),
        ('professor', 'Professor'),
    ]
        
    nome = models.CharField(max_length=70)
    funcao = models.CharField(choices=funcao, blank=True, default='aluno', max_length=10)
    linkLusofona = models.URLField(max_length = 200, blank=True)
    linkLinkedin = models.URLField(max_length = 200, blank=True)

    def __str__(self):
        return self.nome


#Uma pessoa pode ter varios comentários
class Post(models.Model):
    titulo = models.CharField(max_length=50)
    autor = models.ForeignKey(Pessoa, on_delete = models.CASCADE, related_name = "autor")
    data = models.DateTimeField(auto_now_add=True)
    descricao = models.TextField(max_length=1000)
    link = models.CharField(max_length=200, blank=True)
    imagem = models.ImageField(upload_to="static/portfolio/images", blank=True)

    def __str__(self):
        return self.titulo[:50]
    

class Tecnologia(models.Model):
    nome = models.CharField(max_length=30)
    ano = models.DateTimeField(auto_now_add=True)
    criador = models.CharField(max_length=40)
    logo = models.ImageField(upload_to="static/portfolio/images", blank=True)
    link = models.URLField(max_length = 200)
    descricao = models.TextField(max_length=1000)

    def __str__(self):
        return self.nome[:50]
    
class Projeto(models.Model):
    titulo = models.CharField(max_length=50)
    descricao =  models.TextField(max_length=2000)
    imagem = models.ImageField(upload_to="static/portfolio/images", blank=True)
    ano = models.IntegerField(default=2023)
    linkGithub = models.URLField(max_length=1000,  blank=True)
    linkYoutube = models.URLField(max_length=1000,  blank=True)
    participantes = models.ManyToManyField(Pessoa)
    tecnologias = models.ManyToManyField(Tecnologia)

    def __str__(self):
        return self.titulo[:50]
    


class Cadeira(models.Model):
    ano = [
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
    ]

    semestre = [
        ('1', '1'),
        ('2', '2'),
    ]

    rank = [
        ('1', '1'),('2', '2'),('3', '3'),('4', '4'),('5', '5'),
    ]

    nome = models.CharField(max_length=40)
    anoLectivo = models.CharField(max_length=10,choices= ano, default=1)
    semestre = models.CharField(max_length=4,choices= semestre, default=1)
    ano = models.IntegerField(default=2021)
    ects = models.IntegerField()
    topicosAbordados = models.TextField(max_length=1000, blank=True)
    linguagens = models.ManyToManyField(Tecnologia, blank=True)
    ranking = models.CharField(max_length=2,choices= rank)
    docente_teorica = models.ForeignKey(Pessoa, on_delete=models.CASCADE)
    docentes_praticas = models.ManyToManyField(Pessoa, related_name='docentes')
    link = models.URLField(max_length = 200)
    projetos = models.ManyToManyField(Projeto, blank=True)

    def __str__(self):
        return self.nome[:50]
    

class Competencia(models.Model):
    titulo = models.CharField(max_length=50)
    descricao = models.CharField(max_length=1000)
    projetos = models.ManyToManyField(Projeto)
    disciplinas = models.ManyToManyField(Cadeira)
    
    def __str__(self):
        return self.titulo[:50]

class Interesse(models.Model):
    titulo = models.CharField(max_length=50)
    descricao = models.TextField(max_length=1000)
    imagem = models.ImageField(upload_to="static/portfolio/images", blank=True)
    link = models.URLField(max_length = 200, blank=True)

    def __str__(self):
        return self.titulo[:50]
    
class Laboratorio(models.Model):
    titulo = models.CharField(max_length=50)
    descricao = models.TextField(max_length=1000)
    link = models.URLField(max_length = 200)

    def __str__(self):
        return self.titulo[:50]
    

class Noticia(models.Model):
    titulo = models.CharField(max_length=50)
    descricao = models.CharField(max_length=1000)
    link = models.CharField(max_length=1000)
    imagem = models.URLField(max_length = 200)

    def __str__(self):
        return self.titulo[:50]
    

class Tfc(models.Model):
    autor = models.ManyToManyField(Pessoa, related_name = "autorTFC")
    orientadores = models.ManyToManyField(Pessoa, related_name='orientadores')
    ano = models.IntegerField(default=2023)
    titulo = models.CharField(max_length=50)
    resumo = models.CharField(max_length=1000)
    imagem = models.ImageField(upload_to="static/portfolio/images", blank=True)
    relatorio = models.URLField(max_length=1000)
    linkGithub = models.URLField(max_length=1000, blank=True)
    video = models.URLField(max_length=1000)

    def __str__(self):
        return self.titulo[:50]
    

portfolio/forms.py
from django import forms
from django.forms import ModelForm
from .models import *
from django.contrib.auth import get_user_model

class PostForm(ModelForm):
    autor = forms.ModelChoiceField(queryset=Pessoa.objects.all())

    class Meta:
        model = Post
        fields = ['titulo', 'autor', 'descricao', 'link','imagem']

    # inserção de classes CSS para formatação de cada campo do formulário
        widgets = {
            'autor': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'autor'}),
            'titulo': forms.TextInput(attrs={'class': 'form-control', 'placeholder' : 'titulo'}),
            'link': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'link'}),
            'descricao': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'descricao'}),
        }


    # texto a exibir junto à janela de inserção
        labels = {
            'autor': 'Autor',
            'titulo': 'Título',
            'link': 'Link',
            'descricao': 'Descrição',
        }

#CADEIRAS FORM 
class CadeiraForm(forms.ModelForm):
    class Meta:
        model = Cadeira
        fields = '__all__'

#CADEIRAS FORM 
class ProjetoForm(forms.ModelForm):
    class Meta:
        model = Projeto
        fields = '__all__'

portfolio/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from portfolio.forms import CadeiraForm, PostForm, ProjetoForm
from django.contrib.auth.decorators import login_required
from .models import *


def home_view(request):
    return render(request, 'portfolio/home.html')


def projects_view(request):
    context = {'projetos': Projeto.objects.all(), 'tfcs': Tfc.objects.all()}
    return render(request, 'portfolio/projects.html',context)


def technologys_view(request):
    context = {'techs': Tecnologia.objects.all()}
    return render(request, 'portfolio/technologys.html',context)


def labs_view(request):
    context = {'labs': Laboratorio.objects.all()}
    return render(request, 'portfolio/labs.html',context)

def usedtech_view(request):
    return render(request, 'portfolio/usedtech.html')


def javascript_view(request):
    return render(request, 'portfolio/javascript.html')


def university_view(request):
    context = {'cadeiras': Cadeira.objects.all()}
    return render(request, 'portfolio/university.html',context)


def education_view(request):
    return render(request, 'portfolio/education.html')


def skills_view(request):
    context = {'competencias' : Competencia.objects.all()}
    return render(request, 'portfolio/skills.html', context)


def hobbies_view(request):
    context = {'hobbies' : Interesse.objects.all()}
    return render(request, 'portfolio/hobbies.html',context)


def aboutme_view(request):
    return render(request, 'portfolio/aboutme.html')


def blog_view(request):
    context = {'posts': Post.objects.all(), 'noticias' : Noticia.objects.all()}
    return render(request, 'portfolio/blog.html', context)


def contact_view(request):
    return render(request, 'portfolio/contact.html')


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request,
                           username=username,
                           password=password)
        
        if user is not None:
            login(request, user)
            return redirect('portfolio:home')
        else:
            return render(request, 'portfolio/login.html', {
                'message': 'Credenciais invalidas',
            })
    return render(request, 'portfolio/login.html')


def logout_view(request):
    logout(request)
    return redirect('portfolio:home')


@login_required
def criar_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('portfolio:blog')  # Redirecione para uma página de sucesso após a criação do post
    else:
        form = PostForm()
        pessoas = Pessoa.objects.all()
    return render(request, 'portfolio/criar.html', {'form': form, 'autor':pessoas})

@login_required
def edita_comentario(request, comentario_id):
    comentario = Post.objects.get(id=comentario_id)
    form = PostForm(request.POST or None, instance=comentario)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:blog'))

    context = {'form': form, 'comentario_id': comentario_id}
    return render(request, 'portfolio/editar.html', context)

def apagar_comentario(request, comentario_id):
    Post.objects.get(id=comentario_id).delete()
    return HttpResponseRedirect(reverse('portfolio:blog'))




# CRIAÇÃO DE NOVA CADEIRA --
@login_required
def criar_cadeira(request):
    if request.method == 'POST':
        form = CadeiraForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('portfolio:licenciatura')  # Redirecione para uma página de sucesso após a criação do post
    else:
        form = CadeiraForm()
    return render(request, 'portfolio/criarcadeira.html', {'form': form})

@login_required
def apagar_cadeira(request, cadeira_id):
    Cadeira.objects.get(id=cadeira_id).delete()
    return HttpResponseRedirect(reverse('portfolio:licenciatura'))




# CRIAÇÃO DE NOVO PROJETO --
@login_required
def criar_projeto(request):
    if request.method == 'POST':
        form = ProjetoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('portfolio:projetos')  # Redirecione para uma página de sucesso após a criação do post
    else:
        form = ProjetoForm()
    return render(request, 'portfolio/criarprojeto.html', {'form': form})

@login_required
def apagar_projeto(request, projeto_id):
    Projeto.objects.get(id=projeto_id).delete()
    return HttpResponseRedirect(reverse('portfolio:projetos'))

portfolio/templates/portfolio/blog.html
{% extends 'portfolio/layout.html' %}


{% load static %}

{% block style %}

<title>Blog</title>
<link rel="icon" href="{% static '/images/blog.png' %}">

   

<style>

.hobbies-info h2 {
 font-size: 1.25em;
}
.card{
    text-align: center;
}

.button {
    background-color: #4c9baf;
    border: none;
    border-radius: 10px;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
  }
</style>
{% endblock %}


{% block main %}
    
    <div class="blogContainer">
        <div class="row">
            <div class="header">
                <h1>Blog</h1>
                <p>Comentários neste Blog</p>
            </div>
            
                <div class="contentContainer">
                    {% for post in posts %}
                    <div class="card">
                        <img src="{{post.imagem.url}}" style="max-width: 100px;" alt="Blog 1">
                        <h4>{{post.titulo}}</h4>
                        <h2>{{post.data}}</h2>
                        <h2>{{post.autor}}</h2>
                        <p>{{post.descricao}}</p>
                        {% if request.user.is_authenticated %}
                        <a href="{% url 'portfolio:editar' post.id %}" class="button" style="float: right; margin-right: 10px;">Editar</a>
                        {% endif %}
                        
                    </div>

                    {% endfor %}
                </div>
            {% if request.user.is_authenticated %}
            <a href="{% url 'portfolio:criar' %}" class="button">+ Novo comentário</a>
            {% endif %}
        </div>

    </div>

    <h1 style="text-align: center;">Notícias</h1>
    <section class="hobbies-section">
        {%for noticia in noticias %}
            <div class="hobbies-info">
                <div>
                    <h2>{{noticia.titulo}}</h2>
                    <img src="{{noticia.imagem}}" alt="{{noticia.titulo}}">
                </div>
                <div>
                    <p>{{noticia.descricao}}</p>
                    <a href="{{noticia.link}}">Visitar</a>
                </div>
            </div>
        {% endfor %}
    </section>

{% endblock %}

portfolio/templates/portfolio/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load static %}


    <!-- JQUERY -->
    <script
  src="https://code.jquery.com/jquery-3.6.4.js"
  integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E="
  crossorigin="anonymous"></script>

    <!-- CSS REF -->
    <link rel="stylesheet" href="{% static '/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <!-- Font REF -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700&display=swap" rel="stylesheet">


    {% block style %}
    {% endblock %}
</head>
<body>


    <header>
        <div class="nav">
            <ul class="menu">
                <div class="close-btn"></div>

                <li class="menu-item"><a href="{% url 'portfolio:home' %}">Home</a></li>


                <li class="menu-item"><a class="sub-btn" href="{% url 'portfolio:projetos' %}">Projetos <i class="fa fa-angle-down" aria-hidden="true"></i></a>
                    <ul class="sub-menu">
                        <li class="sub-item"><a href="{% url 'portfolio:projetos' %}">Universidade</a></li>
                    </ul>
                </li>



                <li class="menu-item"><a class="sub-btn" href="{% url 'portfolio:tecnologias' %}">Progr. Web <i class="fa fa-angle-down" aria-hidden="true"></i></a>
                    <ul class="sub-menu">
                        <li class="sub-item more">
                            <a class="more-btn" href="{% url 'portfolio:tecnologias' %}">Tecnologias <i class="fa fa-angle-right" aria-hidden="true"></i></a>
                            <ul class="more-menu">
                                <li class="more-item"><a href="{% url 'portfolio:tecnologias' %}">Front-End</a></li>
                                <li class="more-item"><a href="{% url 'portfolio:tecnologias' %}">Back-End</a></li>
                            </ul>
                        </li>
                        <li class="sub-item"><a href="{% url 'portfolio:laboratorios' %}">Laboratórios</a></li>
                    </ul>
                </li>


                <li class="menu-item"><a href="{% url 'portfolio:tecusada' %}" class="sub-btn">Este website <i class="fa fa-angle-down" aria-hidden="true"></i></a>
                    <ul class="sub-menu">
                        <li class="sub-item"><a href="{% url 'portfolio:tecusada' %}">Tecnologias Usadas</a></li>
                        <li class="sub-item"><a href="{% url 'portfolio:javascript' %}">Javascript</a></li>
                    </ul>

                </li>

                <li class="menu-item">
                    <a class="sub-btn" href="{% url 'portfolio:sobre' %}">Sobre mim <i class="fa fa-angle-down" aria-hidden="true"></i></a>
                    <ul class="sub-menu">
                        <li class="sub-item more">
                            <a class="more-btn" href="{% url 'portfolio:licenciatura' %}">Licenciatura</a>
                        </li>
                        <li class="sub-item more">
                            <a href="{% url 'portfolio:educacao' %}">Educação</a>

                        </li>
                        <li class="sub-item more">
                            <a href="{% url 'portfolio:skills' %}">Skills</a>

                        </li>
                        <li class="sub-item"><a href="{% url 'portfolio:hobbies' %}">Hobbies</a></li>
                        <li class="sub-item"><a href="{% url 'portfolio:sobre' %}">Sobre Mim</a></li>
                    </ul>
                </li>

                <li class="menu-item"><a href="{% url 'portfolio:blog' %}">Blog</a></li>

                <li class="menu-item"><a href="{% url 'portfolio:contacto' %}">Contacto</a></li>


                {% if request.user.is_authenticated %}

                <li class="menu-item"><a href="{% url 'portfolio:logout' %}">{{request.user}} Logout</a></li>
                {% else %}
                <li class="menu-item"><a href="{% url 'portfolio:login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>

        <div class="menu-btn"></div>
    </header>



    {% block main %}

    {% endblock %}


    <footer>
        <div class="social">
            <a href="https://github.com/bernardo-taciano-a22107478"><i class="fab fa-github" aria-hidden="true"></i></a>
            <a href="https://www.linkedin.com/in/bernardo-taciano/"><i class="fab fa-linkedin" aria-hidden="true"></i></a>
        </div>

        <ul class="list">
            <li>
                <a href="{% url 'portfolio:home' %}">Home</a>
            </li>
            <li>
                <a href="{% url 'portfolio:sobre' %}">Sobre Mim</a>
            </li>
            <li>
                <a href="{% url 'portfolio:blog' %}">Blog</a>
            </li>
            <li>
                <a href="{% url 'portfolio:contacto' %}">Contacto</a>
            </li>
        </ul>
        <p class="copyright">Universidade Lusófona | Engenharia Informática</p>
        <p class="copyright">Bernardo Taciano - a22107478</p>
    </footer>

    <script>
        var menu = document.querySelector(".menu");
        var menuBtn = document.querySelector(".menu-btn");
        var closeBtn = document.querySelector(".close-btn");

        menuBtn.addEventListener("click", () => {
            menu.classList.add("active");
        });

        closeBtn.addEventListener("click", () => {
            menu.classList.remove("active");
        })
    </script>
</body>
</html>

portfolio/templates/portfolio/projects.html
{% extends 'portfolio/layout.html' %}

{% load static %}

{% block style %}
    <title>Projectos</title>
    <link rel="icon" href="{% static '/images/projects.png' %}">

    <style>
        img {
            margin: auto;
            border-radius: 20px;
        }
        .project-year {
            font-size: 12px;
            color: #999;
        }
        .project-link {
            display: inline-block;
            margin-top: 20px;
            font-size: 14px;
            font-weight: bold;
            color: #333;
            text-decoration: none;
            border-bottom: 2px solid #333;
            transition: border-bottom-color 0.3s ease-in-out;
        }
        .project-link:hover {
            border-bottom-color: #666;
        }
        .technologies {
            margin-top: 20px;
        }
        .technology {
            display: inline-block;
            margin-right: 10px;
            padding: 5px 10px;
            background-color: #ccc;
            border-radius: 5px;
            font-size: 12px;
            color: #333;
            text-decoration: none;
            transition: background-color 0.3s ease-in-out;
        }
        .technology:hover {
            background-color: #666;
            color: #fff;
        }

        .list-project {
            text-align: center;
            padding: 40px;
            display: flex;
            gap: 30px;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            background-color: #e9e9e9;
            width: 700px;
            border-radius: 20px;
            margin: 10px auto;
        }

        .list-project p {
            font-weight: 700;
            line-height: 1.5;
            text-align: justify;
            max-width: 700px;
        }

        .list-project a {
            color: black;
            text-decoration: underline;
            font-weight: bold;
        }

        @media (max-width: 991px){
            img {
                max-width: 300px;
            }
            .list-project  {
                padding: 10px;
            }
        }
    </style>

{% endblock %}




{% block main %}

    <div class="this-website-header">
        <h2>Projetos Universidade</h2>
    </div>

    <ul>
        <li class="list-project">
            {% if request.user.is_authenticated %}
            <a href="{% url 'portfolio:criarprojeto' %}" class="button">+ Adicionar Projeto</a>
            {% endif %}
        </li>
        {% for projeto in projetos %}
            <li class="list-project">

                <h2>{{projeto.titulo}}</h2>
                {% if projeto.imagem.url != '' %}
                    <a href=""><img src="{{projeto.imagem.url}}" width="600px" alt="Projeto Fundamentos De Programação"></a>
                {% endif %}
                <p>{{projeto.descricao}}</p>
                <b>Linguagem:</b>
                {% for linguagem in projeto.tecnologias.all %}
                    <il>{{linguagem}}</il>
                {% endfor %}
                <div class="project-course"><b>Ano de realização</b>: {{projeto.ano}}º</div>
                <b>Participantes:</b>
                {% for autores in projeto.participantes.all %}
                    <div class="project-participants">{{autores}}</div>
                {% endfor %}
                {% if request.user.is_authenticated %}
                    <a href="{% url 'portfolio:apagarprojeto' projeto_id=projeto.id %}" role="button">Apagar</a>
                {% endif %}
            </li>

        {% endfor %}
    </ul>


    <hr>


    <ul>
        <h1 style="text-align: center;">Trabalhos Finais De Curso</h1>
        {% for tfc in tfcs %}
            <li class="list-project">

                <h2>{{tfc.titulo}}</h2>
                <b>Autor(es):</b>
                {% for autores in tfc.autor.all %}
                    <div class="project-participants">{{autores}}</div>
                {% endfor %}
                <b>Orientador(es):</b>
                {% for orientador in tfc.orientadores.all %}
                    <div class="project-participants">{{orientador}}</div>
                {% endfor %}
                <p>{{tfc.ano}}</p>
                <p>{{tfc.resumo}}</p>
                <a href="{{tfc.relatorio}}">Link Relatorio</a>

            </li>
        {% endfor %}
    </ul>

{% endblock %}

portfolio/templates/portfolio/university.html
{% extends 'portfolio/layout.html' %}

{% load static %}

{% block style %}
    <title>Licenciatura</title>
    <link rel="icon" href="{% static '/images/universidade.png' %}">

    <style>
    .titulo_seccao{
        padding: 80px 0 20px 0;
    }   

    .button {
            padding: 25px;
            margin: 25px;
            border: 0;
                    outline: 0;
                    cursor: pointer;
                    color: rgb(60, 66, 87);
                    background-color: rgb(255, 255, 255);
                    box-shadow: rgb(0 0 0 / 0%) 0px 0px 0px 0px, rgb(0 0 0 / 0%) 0px 0px 0px 0px, rgb(0 0 0 / 12%) 0px 1px 1px 0px, rgb(60 66 87 / 16%) 0px 0px 0px 1px, rgb(0 0 0 / 0%) 0px 0px 0px 0px, rgb(0 0 0 / 0%) 0px 0px 0px 0px, rgb(60 66 87 / 8%) 0px 2px 5px 0px;
                    border-radius: 4px;
                    font-size: 14px;
                    font-weight: 500;
                    padding: 4px 8px;
                    display: inline-block;
                    min-height: 28px;
                    transition: background-color .24s,box-shadow .24s;
                    
                
        }

        .button:hover {
            box-shadow: rgb(0 0 0 / 0%) 0px 0px 0px 0px, rgb(0 0 0 / 0%) 0px 0px 0px 0px, rgb(0 0 0 / 12%) 0px 1px 1px 0px, rgb(60 66 87 / 16%) 0px 0px 0px 1px, rgb(0 0 0 / 0%) 0px 0px 0px 0px, rgb(60 66 87 / 8%) 0px 3px 9px 0px, rgb(60 66 87 / 8%) 0px 2px 5px 0px;
        }
    </style>
    
    
{% endblock %}

{% block main %}

    <h1 class="titulo_seccao">Unidades Curriculares</h1>
    <div class="licenciatura">
        {% if request.user.is_authenticated %}
            <a href="{% url 'portfolio:criarcadeira' %}" class="button">+ Adicionar Cadeira</a>
        {% endif %} 

            {% for cadeira in cadeiras %}
                    <div>
                        <h3><a href="{{cadeira.link}}" class="titulo">{{cadeira.nome}}</a></h3>
                        <p><b>ECTS: </b>{{cadeira.ects}}</p>
                        <p><b>Ano Letivo: </b> {{cadeira.anoLectivo}}º</p>
                        <p><b>Semestre: </b>{{cadeira.semestre}}º</p>
                        <p><b>Ano: </b>{{cadeira.ano}}</p>
                        <p><b>Tópicos abordados: </b>{{cadeira.topicosAbordados}}</p>
                        {% if cadeira.linguagens.all.count > 0 %}
                            <p><b>Linguagens: </b> {% for linguagem in cadeira.linguagens.all %} {{linguagem.nome}}{% endfor %}</p>
                        {% endif %}
                        <p><b>Ranking (0-5): </b>{{cadeira.ranking}}</p>
                        <p><b>Docente Teórica: </b><a href="{{cadeira.docente_teorica.linklusofona}}" class="links">{{cadeira.docente_teorica.nome}} {{cadeira.docente_teorica.apelido}}</a></p>
                        <p><b>Docente Práticas: </b> 
                            {% for docente_pratica in cadeira.docentes_praticas.all %}
                                <a href="{{docentes_praticas.linklusofona}}" class="links"> {{docente_pratica.nome}} {{docente_pratica.apelido}}</a> 
                            {% endfor %}
                        </p>
                        {% if cadeira.projetos.all.count > 0  %}
                            <p>
                                <b>Projetos: </b>
                                {% for projeto in cadeira.projetos.all %}
                                <a href="{% url 'portfolio:projetos' %}" class="links">{{projeto.titulo}}</a> 
                                {% endfor %}
                            </p>
                        {% endif %}

                        {% if request.user.is_authenticated %}
                            <a href="{% url 'portfolio:apagarcadeira' cadeira.id %}">Apagar Cadeira</a>
                        {% endif %} 
                    </div>
            {% endfor %}
    </div>    

{% endblock %}